# PlantUML Editor
# Authors:
#   Huyen Minh Nguyen (Fresher Developer)
# Contributors:
#   Viet Pham (Newbie)

@startuml ChickenCommerce
package ChickenCommerceHost {

  package Modules {
    package Account {

      package Infrastructure {
        [Repositories]
        [EventBusClient]
      }

      package Endpoints {
        [API Endpoints] #Yellow
        [GRPC Endpoints] #Yellow
        [Event Handlers] #Yellow
      }

      package Core {
        [Services] #Yellow
        [IEventBusClient]
        [Biz Models]
        [IRepositories]
      }

      [API Endpoints] --> [Services]
      [GRPC Endpoints] --> [Services]
      [Event Handlers] --> [Services]

      [Services] --> [IRepositories] : 1. Fetch Biz Models
      [Services] --> [Biz Models] : 2. Process Biz
      [Services] --> [IRepositories] : 3. Persist Data
      [Services] --> [IEventBusClient] : 4. Publish Event

      [Repositories] ..|> [IRepositories]
      [EventBusClient] ..|> [IEventBusClient]
    }
  }
}

[Client]
Client --> [API Endpoints]
Client --> [GRPC Endpoints]
Client --> [Event Handlers]

package Kafka {
  [Producer]
  [Consumer]
  [Server]

  [Producer] --> [Server]
  [Server] --> [Consumer]

  [Producer] ..|> [EventBusClient]
  [Consumer] ..|> [Event Handlers]
}

database MongoDB
MongoDB ..|> Repositories


@enduml
