# PlantUML Editor
# Author Huyen Minh Nguyen
# Fresher Developer

@startuml
package ChickenCommerce{

package DomainLayer{
[AccountantApi] #Yellow
[ProductApi] #Yellow
[KafkaConsumer]
[KafkaProducer]
[BusinessLayer]

AccountantApi --> BusinessLayer
ProductApi --> BusinessLayer
KafkaConsumer --> BusinessLayer
BusinessLayer --> KafkaProducer
}
}

[Kafka]
KafkaProducer --> Kafka
Kafka --> KafkaConsumer

[Frontend]

Frontend --> AccountantApi : CRUD operations
Frontend --> ProductApi : CRUD operations

database MongoDB
AccountantApi --> MongoDB
ProductApi --> MongoDB

@enduml
