# PlantUML Editor
# Authors:
#   Huyen Minh Nguyen (Fresher Developer)
# Contributors:
#   Viet Pham (Newbie)

@startuml ChickenCommerce
package ChickenCommerceHost {

  [AuthMiddleware]

  package Modules {

    package Account {

      package AccInfra {
        [AccRepos]
        [AccEventBusClient]
      }

      package AccEndpoints {
        [AccAPIs] #Yellow
        [AccGRPCs] #Yellow
        [AccEvents] #Yellow
      }

      package AccCore {
        [IAccServices] #Yellow
        [AccServices]
        [IAccEventBusClient]
        [Acc Biz Models]
        [IAccRepos]
      }

      [AccServices] ..|> [IAccServices]

      [AccAPIs] --> [IAccServices]
      [AccGRPCs] --> [IAccServices]
      [AccEvents] --> [IAccServices]

      [IAccServices] --> [IAccRepos] : 1. Fetch Biz Models
      [IAccServices] --> [Acc Biz Models] : 2. Process Biz
      [IAccServices] --> [IAccRepos] : 3. Persist Data
      [IAccServices] --> [IAccEventBusClient] : 4. Publish Event

      [AccRepos] ..|> [IAccRepos]
      [AccEventBusClient] ..|> [IAccEventBusClient]
    }

    package Catalog {

      package CatalogInfra {
        [CatalogRepos]
        [CatalogEventBusClient]
      }

      package CatalogEndpoints {
        [CatalogAPIs] #Yellow
        [CatalogGRPCs] #Yellow
        [CatalogEvents] #Yellow
      }

      package CatalogCore {
        [ICatalogServices] #Yellow
        [CatalogServices]
        [ICatalogEventBusClient]
        [Catalog Biz Models]
        [ICatalogRepos]
      }

      [CatalogServices] ..|> [ICatalogServices]

      [CatalogAPIs] --> [ICatalogServices]
      [CatalogGRPCs] --> [ICatalogServices]
      [CatalogEvents] --> [ICatalogServices]

      [ICatalogServices] --> [ICatalogRepos] : 1. Fetch Biz Models
      [ICatalogServices] --> [Catalog Biz Models] : 2. Process Biz
      [ICatalogServices] --> [ICatalogRepos] : 3. Persist Data
      [ICatalogServices] --> [ICatalogEventBusClient] : 4. Publish Event

      [CatalogRepos] ..|> [ICatalogRepos]
      [CatalogEventBusClient] ..|> [ICatalogEventBusClient]
    }

  }
}

[Client]
Client --> [AuthMiddleware]

[AuthMiddleware] --> [AccAPIs]
[AuthMiddleware] --> [AccGRPCs]
[AuthMiddleware] --> [AccEvents]
[AuthMiddleware] --> [CatalogAPIs]
[AuthMiddleware] --> [CatalogGRPCs]
[AuthMiddleware] --> [CatalogEvents]

package Kafka {
  [Producer]
  [Consumer]
  [Server]

  [Producer] --> [Server]
  [Server] --> [Consumer]

  [Producer] ..|> [AccEventBusClient]
  [Consumer] ..|> [AccEvents]
  
  [Producer] ..|> [CatalogEventBusClient]
  [Consumer] ..|> [CatalogEvents]
}

database MongoDB
MongoDB ..|> [AccRepos]
MongoDB ..|> [CatalogRepos]

@enduml
