# PlantUML Editor
# Authors:
#   Huyen Minh Nguyen (Fresher Developer)
# Contributors:
#   Viet Pham (Newbie)

@startuml ChickenCommerce
package ChickenCommerceHost {

  [AuthMiddleware]

  package Modules {

    package Order {

      package OrderInfra {
        [OrderRepos]
        [OrderEventBusClient]
      }

      package OrderEndpoints {
        [OrderAPIs] #Yellow
        [OrderEvents] #Yellow
      }

      package OrderCore {
        [IOrderServices] #Yellow
        [OrderServices]
        [IOrderEventBusClient]
        [Order Biz Models]
        [IOrderRepos]
      }

      [OrderServices] ..|> [IOrderServices]

      [OrderAPIs] --> [IOrderServices] : 1.1 Invoke CreateOrder
      [IOrderServices] --> [Order Biz Models] : 1.2 Init Draft Order

      [IOrderServices] --> [IOrderRepos] : 1.3 Persist Draft Order
      [IOrderServices] --> [IOrderEventBusClient] : 1.4 Publish DraftOrderCreated Event

      [OrderEvents] --> [IOrderServices] : 1.12 Invoke SetOrderStatusConfirmed
      
      [IOrderServices] --> [IOrderRepos] : 1.13 Fetch Given Order
      [IOrderServices] --> [IOrderEventBusClient] : 1.14 Process Order Status Transitioning from Draft to Confirmed  
      [IOrderServices] --> [IOrderRepos] : 1.15 Persist Confirmed Order

      [OrderRepos] ..|> [IOrderRepos]
      [OrderEventBusClient] ..|> [IOrderEventBusClient]
    }

    package Catalog {

      package CatalogInfra {
        [CatalogRepos]
        [CatalogEventBusClient]
      }

      package CatalogEndpoints {
        [CatalogEvents] #Yellow
      }

      package CatalogCore {
        [ICatalogServices] #Yellow
        [CatalogServices]
        [ICatalogEventBusClient]
        [Catalog Biz Models]
        [ICatalogRepos]
      }

      
      [CatalogServices] ..|> [ICatalogServices]

      [CatalogEvents] --> [ICatalogServices] : 1.6 Invoke ReserveProducts

      [ICatalogServices] --> [ICatalogRepos] : 1.7 Fetch Catalog Biz Model
      [ICatalogServices] --> [Catalog Biz Models] : 1.8 Process product reservation
      [ICatalogServices] --> [ICatalogRepos] : 1.9 Persist Catalog Biz Model
      [ICatalogServices] --> [ICatalogEventBusClient] : 1.10 Publish ProductReservationSuccessful Event

      [CatalogRepos] ..|> [ICatalogRepos]
      [CatalogEventBusClient] ..|> [ICatalogEventBusClient]
    }

  }
}

[Client]
Client --> [AuthMiddleware]

[AuthMiddleware] --> [OrderAPIs] : 1: Create Order Request

package Kafka {
  [Producer]
  [Consumer]
  [Server]

  [Producer] --> [Server]
  [Server] --> [Consumer]

  [Producer] ..|> [OrderEventBusClient]
  [Consumer] --> [OrderEvents] : 1.11 Trigger ProductReservationSuccessful Handler
  
  [Producer] ..|> [CatalogEventBusClient]
  [Consumer] --> [CatalogEvents] : 1.5 Trigger DraftOrderCreated Handler
}


@enduml
